name: Recovery Builder

on:  
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-20.04    
    steps:    
    - name: Checkout      
      uses: actions/checkout@v2    

    - name: Recovery Build Action      
      uses: Area-73/recovery-builder@main      
      with:        
      MANIFEST_URL: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git        
      MANIFEST_BRANCH: twrp-11        
      DEVICE_PATH: device/samsung/xcover5        
      DEVICE_NAME: xcover5        
      MAKEFILE_NAME: omni_xcover5         
      BUILD_TARGET: recovery
